export const expenseCategories = [
  { label: "Grocery", value: "grocery" },
  { label: "Lunch", value: "lunch" },
  { label: "Dinner", value: "dinner" },
  { label: "Cafe", value: "cafe" },
  { label: "Laundry", value: "laundry" },
  { label: "Rent", value: "rent" },
  { label: "Google Fi", value: "google fi" },
  { label: "Cloud computing", value: "cloud computing" },
  { label: "Education", value: "education" },
  { label: "Leisure", value: "leisure" },
  { label: "Transportation", value: "transportation" },
  { label: "Electronics", value: "electronics" },
  { label: "Clothing", value: "clothing" },
  { label: "Home internet", value: "home internet" },
  { label: "Shipment", value: "shipment" },
  { label: "Commission", value: "commission" },
  { label: "Camping gear", value: "camping gear" },
  { label: "Tennis", value: "tennis" },
  { label: "Bike", value: "bike" },
  { label: "Homeware", value: "homeware" },
  { label: "Tax", value: "tax" },
  { label: "Motorcycle", value: "motorcycle" },
  { label: "Gas", value: "gas" },
  { label: "Piano", value: "piano" },
  { label: "Accessory", value: "accessory" },
];

export const expenseTypes = [
  { label: "Normal", value: "normal" },
  { label: "Special", value: "special" },
];
